name: bloc_practice1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  logger: ^2.6.2
  elegant_notification: ^2.5.1
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.3
  get: ^4.7.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Rubik_Regular
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf

    - family: Rubik_Medium
      fonts:
        - asset: assets/fonts/rubik/Rubik-Medium.ttf

    - family: Rubik_Bold
      fonts:
        - asset: assets/fonts/rubik/Rubik-Bold.ttf

    - family: Rubik_Black
      fonts:
        - asset: assets/fonts/rubik/Rubik-Black.ttf

    - family: Poppins_Regular
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf

    - family: Poppins_Medium
      fonts:
        - asset: assets/fonts/poppins/Poppins-Medium.ttf

    - family: Poppins_Bold
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf

    - family: Poppins_Black
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
